#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=894361824833
BundleId=com.xtudio16.triviageek
ClientId=894361824833-7hi8f5o9cu9pcf8bild6kiu1rnfl55dg.apps.googleusercontent.com

*/

#define kAppID "894361824833"
#define kBundleID "com.xtudio16.triviageek"
#define kClientID "894361824833-7hi8f5o9cu9pcf8bild6kiu1rnfl55dg.apps.googleusercontent.com"

#endif


